// AUTO-GENERATED by scripts/build-registry.ts — do not edit manually.
// Run: npm run build:registry

import type { ComponentType } from "react"

type DemoModule = { default: ComponentType }

export const registryLoaders: Record<
  string,
  {
    demo: () => Promise<DemoModule>
  }
> = {
  "glsl-hills-hero": {
    demo: () => import("./hero-sections/glsl-hills-hero/demo"),
  },
  "new-hero": {
    demo: () => import("./hero-sections/new-hero/demo"),
  },
}
