// AUTO-GENERATED by scripts/build-registry.ts — do not edit manually.
// Run: npm run build:registry

export const codePaths: Record<string, string[]> = {
  "glsl-hills-hero": [
    "hero-sections/glsl-hills-hero/demo.tsx",
    "hero-sections/glsl-hills-hero/ui/glsl-hills.tsx",
  ],
}
